language: node_js

node_js:
  - "10"
  - "8"

script:
  - yarn test
  - yarn danger ci

branches:
  only:
    - master
    - /^greenkeeper/.*$/

after_success:
  - npm run semantic-release

cache: yarn
